categorical_features:
  market_type:
    num_classes: 2
  sector:
    num_classes: 4
  symbol:
    num_classes: 5
  trade_type:
    num_classes: 3
numerical_features:
- price
- volume
- volatility
- market_cap
